name: dbt_md_hechos_hist
version: 1.0.0
config-version: 2

profile: dbt_md_hechos_hist

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  dbt_md_hechos_hist:
    +materialized: view
    staging:
      +tags: ["staging"]
    intermediate:
      +tags: ["intermediate"]
    marts:
      +tags: ["mart"]
