version: 2

sources:
  - name: stage
    database: BMV_STAGE_ADM
    schema: BMV_STAGE_ADM
    tables:
      - name: STG_THECHOS_MXD
      - name: STG_TSPLITS
      - name: STG_MXD_EMISORAS

  - name: historico
    database: MEXDER_HISTORICO_ADM
    schema: MEXDER_HISTORICO_ADM
    tables:
      - name: MD_CAT_INSTRUMENTOS
      - name: MD_CAT_LIQUIDADORES

  - name: dwh
    database: DWH_ADM
    schema: DWH_ADM
    tables:
      - name: DWH_CAT_TIPOS_VALORES
      - name: DWH_CAT_TIPO_CONCERTACION
      - name: D_CASAS_BOLSA

  - name: operaciones
    database: BMV_OPERACIONES_ADM
    schema: BMV_OPERACIONES_ADM
    tables:
      - name: CAT_PARAMETROS
      - name: OPE_CCONCERTACIONES
      - name: OPE_TENTIDADES
      - name: OPE_TCUENTAS_LIQUIDACIONES
      - name: OPE_TASIGNACION_LIQ_ENTIDAD
      - name: COM_CBOLSAS_VALORES
